"use strict";
const bcrypt = require("bcrypt");
const { SALT_ROUNDS } = require("../config/constants");

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      "users",
      [
        {
          email: "brenda@gmail.com",
          password: bcrypt.hashSync("brenda", SALT_ROUNDS),
          firstName: "Brenda",
          lastName: "Rietman",
          address: "Linnaeusstraat 43, 1093EG Amsterdam",
          phoneNum: null,
          createdAt: new Date(),
          updatedAt: new Date(),
          isOwner: false,
        },
        {
          email: "nyckele@gmail.com",
          password: bcrypt.hashSync("nyckele", SALT_ROUNDS),
          firstName: "Nyckele",
          lastName: "Sap",
          address: "Dick Greinerstraat 60, 1019CV Amsterdam",
          phoneNum: null,
          createdAt: new Date(),
          updatedAt: new Date(),
          isOwner: false,
        },
        {
          email: "david@gmail.com",
          password: bcrypt.hashSync("david", SALT_ROUNDS),
          firstName: "David",
          lastName: "Knappstein",
          address: "Laurierhof 18, 1016MA Amsterdam",
          phoneNum: null,
          createdAt: new Date(),
          updatedAt: new Date(),
          isOwner: true,
        },
        {
          email: "linda@gmail.com",
          password: bcrypt.hashSync("linda", SALT_ROUNDS),
          firstName: "Linda",
          lastName: "Smith",
          address: "Eerste Helmersstraat 106, 1054EG Amsterdam",
          phoneNum: null,
          createdAt: new Date(),
          updatedAt: new Date(),
          isOwner: false,
        },
        {
          email: "john@gmail.com",
          password: bcrypt.hashSync("john", SALT_ROUNDS),
          firstName: "John",
          lastName: "Jackson",
          address: "Bos en Vaartlaan, 1181AA Amstelveen",
          phoneNum: null,
          createdAt: new Date(),
          updatedAt: new Date(),
          isOwner: false,
        },
        {
          email: "vesna@gmail.com",
          password: bcrypt.hashSync("vesna", SALT_ROUNDS),
          firstName: "Vesna",
          lastName: "Smith",
          address: "Overtoom 371, 1054JN Amsterdam",
          phoneNum: null,
          createdAt: new Date(),
          updatedAt: new Date(),
          isOwner: true,
        },
        {
          email: "emma@gmail.com",
          password: bcrypt.hashSync("emma", SALT_ROUNDS),
          firstName: "Emma",
          lastName: "Johnson",
          address: "Bos en Lommer, 1055RZ Amsterdam",
          phoneNum: null,
          createdAt: new Date(),
          updatedAt: new Date(),
          isOwner: false,
        },
        {
          email: "akke@gmail.com",
          password: bcrypt.hashSync("akke", SALT_ROUNDS),
          firstName: "Akke",
          lastName: "Reijnhoudt",
          address: "Wijnand Nuijenstraat 91, 1061WB Amsterdam",
          phoneNum: null,
          createdAt: new Date(),
          updatedAt: new Date(),
          isOwner: false,
        },
        {
          email: "guido@gmail.com",
          password: bcrypt.hashSync("guido", SALT_ROUNDS),
          firstName: "Guido",
          lastName: "Los",
          address: "Johannes van der Steurstraat 24, 1066BN Amsterdam",
          phoneNum: null,
          createdAt: new Date(),
          updatedAt: new Date(),
          isOwner: false,
        },
        {
          email: "kees@gmail.com",
          password: bcrypt.hashSync("kees", SALT_ROUNDS),
          firstName: "Kees",
          lastName: "Smith",
          address: "Haarlemmerweg 10A, 1014BE Amsterdam",
          phoneNum: null,
          createdAt: new Date(),
          updatedAt: new Date(),
          isOwner: true,
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("users", null, {});
  },
};
